publish:
  description: Publish resulting STAC Collections and Items to catalog, and optionally SNS
  handler: lambda_function.lambda_handler
  memorySize: 128
  timeout: 30
  module: tasks/publish

pre-batch:
  description: Pre process batch job by copying input to S3
  handler: lambda_function.lambda_handler
  memorySize: 128
  timeout: 15
  module: tasks/pre-batch

post-batch:
  description: Post process batch job by copying input from S3
  handler: lambda_function.lambda_handler
  memorySize: 128
  timeout: 15
  module: tasks/post-batch

copy-assets:
  description: Copy specified assets from Item(s) to an S3 bucket
  handler: lambda_function.lambda_handler
  memorySize: 768
  timeout: 60
  module: tasks/copy-assets

convert-to-cog:
  description: Convert specified assets into Cloud Optimized GeoTIFFs
  handler: lambda_function.lambda_handler
  memorySize: 1024
  timeout: 900
  module: tasks/convert-to-cog
  environment:
    GDAL_DATA: /opt/share/gdal
    PROJ_LIB: /opt/share/proj
  layers:
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda:2
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda-python:1

add-preview:
  description: Create a preview and/or thumbnail from one or more assets
  handler: lambda_function.lambda_handler
  memorySize: 1024
  timeout: 900
  module: tasks/add-preview
  environment:
    GDAL_DATA: /opt/share/gdal
    PROJ_LIB: /opt/share/proj
  layers:
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda:2
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda-python:1

sentinel-to-stac:
  description: Convert Sentinel metadata (tileInfo.json) to STAC
  handler: lambda_function.lambda_handler
  memorySize: 128
  timeout: 300
  module: tasks/sentinel-to-stac
  environment:
    GDAL_DATA: /opt/share/gdal
    PROJ_LIB: /opt/share/proj
  layers:
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda:2
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda-python:1

landsat-to-stac:
  description: Convert Landsat metadata (MTL.txt, ANG.txt) to STAC
  handler: lambda_function.lambda_handler
  memorySize: 128
  timeout: 300
  module: tasks/landsat-to-stac
